/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ReadComicIdRouteImport } from './routes/read.$comicId'
import { Route as StudioMissionIdRouteImport } from './routes/studio.$missionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadComicIdRoute = ReadComicIdRouteImport.update({
  id: '/read/$comicId',
  path: '/read/$comicId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioMissionIdRoute = StudioMissionIdRouteImport.update({
  id: '/studio/$missionId',
  path: '/studio/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/read/$comicId': typeof ReadComicIdRoute
  '/studio/$missionId': typeof StudioMissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/read/$comicId': typeof ReadComicIdRoute
  '/studio/$missionId': typeof StudioMissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/read/$comicId': typeof ReadComicIdRoute
  '/studio/$missionId': typeof StudioMissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/library' | '/read/$comicId' | '/studio/$missionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/read/$comicId' | '/studio/$missionId'
  id: '__root__' | '/' | '/library' | '/read/$comicId' | '/studio/$missionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  ReadComicIdRoute: typeof ReadComicIdRoute
  StudioMissionIdRoute: typeof StudioMissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$comicId': {
      id: '/read/$comicId'
      path: '/read/$comicId'
      fullPath: '/read/$comicId'
      preLoaderRoute: typeof ReadComicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$missionId': {
      id: '/studio/$missionId'
      path: '/studio/$missionId'
      fullPath: '/studio/$missionId'
      preLoaderRoute: typeof StudioMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  ReadComicIdRoute: ReadComicIdRoute,
  StudioMissionIdRoute: StudioMissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
